export default {
  mrz: "Mrz",
  ocr: "Ocr",
  barcode: "Barcode",
  locate: "Locate",
  docType: "DocType",
  mrzOrBarcode: "MrzOrBarcode",
  mrzOrLocate: "MrzOrLocate",
  mrzAndLocate: "MrzAndLocate",
  mrzOrOcr: "MrzOrOcr",
  mrzOrBarcodeOrOcr: "MrzOrBarcodeOrOcr",
  locateVisual_And_MrzOrOcr: "LocateVisual_And_MrzOrOcr",
  fullProcess: "FullProcess",
  id3Rus: "Id3Rus",
};
